

app:
  minio:
    endpoint: "https://192.168.3.7:9009"
    access-key: "minioadmin"
    secret-key: "fangpz@123"
    bucket: "mall-files"
    secure: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: mall-backend
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
      percentiles-histogram:
        http.server.requests: true

